-- AlterTable
ALTER TABLE "DeepWorkSession" ADD COLUMN IF NOT EXISTS "idleMs" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "DeepWorkSession" ADD COLUMN IF NOT EXISTS "productivityScore" DOUBLE PRECISION NOT NULL DEFAULT 0;
